baseURL = "https://fortinetsecdevops.github.io/DemoFrontEnd/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo web framework for Fortinet Demos"
theme = ["hugo-theme-relearn"]
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "false"
uglyurls = "true"
enableEmoji = true

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  #editURL = ""
  # Author of the site, will be used in meta information
  author = "Jingshao Chen"
  # Description of the site, will be used in meta information
  description = "Hugo web framework for Fortinet Demos"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false

  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"

  #!!! Change the theme variable to match the type of training
  themeVariant = "workshop"
  logoBannerText = "Workshop"

  # themeVariant = "demo"
  # logoBannerText = "Demo"

  # themeVariant = "usecase"
  # logoBannerText = "Use Case"

  # themeVariant = "spotlight"
  # logoBannerText = "Spotlight"


  landingPageURL = "/DemoFrontEnd"
  landingPageName = "<i class='fas fa-home'></i> Home"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fas fa-graduation-cap'></i> AWS Sample Workshop"
url = "https://aws-samples.github.io/aws-modernization-workshop-sample/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> Fortinet Standard Workshop Web format - MVP1"
url = "https://fortinetsecdevops.github.io/technical-recipe-azure-sdwan/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> Fortinet Standard Workshop Git Repo - MVP1"
url = "https://github.com/FortinetSecDevOps/technical-recipe-azure-sdwan"
weight = 21

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> Hugo learn theme repo"
url = "https://fortinetsecdevops.github.io/technical-recipe-azure-sdwan/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> Hugo Learn theme - Guide"
url = "https://learn.netlify.app/en/basics/"
weight = 35


[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> Hugo Notice Submodule "
url = "https://github.com/martignoni/hugo-notice"
weight = 40

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    hrefTargetBlank = true
